[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.optimize]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20_000

[profile.monad]
src = "src"
out = "out"
libs = ["lib"]

metadata = true
metadata_hash = "none"  # disable ipfs
use_literal_content = true # use source code

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
localhost = "${LOCALHOST_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
mainnet = { key = "${ETH_API_KEY}", url = "https://etherscan.io" }
sepolia = { key = "${ETH_API_KEY}", url = "https://sepolia.etherscan.io" }
base = { key = "${ETH_API_KEY}", url = "https://basescan.org" }
