[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.optimize]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20_000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
localhost = "${LOCALHOST_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
sepolia = { key = "${ETH_API_KEY}", url = "https://sepolia.etherscan.io" }
base = { key = "${ETH_API_KEY}", url = "https://basescan.org" }
